language: php

git:
  depth: 1

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: 7.1
    - php: 7.2
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge

before_script:
    - composer self-update
    - composer install --no-interaction --dev --prefer-dist

script:
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
